"""
constants for metric conversion

instead of listing out stop words, I'm going to list out compatable metrics
and for each value, iterate through and strip out numerics and operators (./)
reminder to account for plurals (e.g. jigger & jiggers)
"""


# taken from wikipedia
primary_conversion_dict = {
                      'cl': 10,
                      'cup' : 236.59,
                      'dash': .92,
                      'dl'  : 100,
                      'drop' : .05,
                      'fifth': 750,
                      'gal': 3785.412,
                      'tablespoon' : 14.787,
                      'tblsp' : 14.787,
                      'tbsp' : 14.787,
                      'jigger' : 44.3602943, #aka a shot
                      'ml' : 1,
                      'ounce' : 29.574,
                      'oz' : 29.574,
                      'pony': 29.57,
                      'pinch' : .31,
                      'pint' : 568.261,
                      'pt' : 568.261,
                      'qt' : 946.35,
                      'quart' : 946.35,
                      'shot'  : 44.3602943,
                      'snit' : 88.72,
                      'splash' : 5.91,
                      'split' : 177.44,
                      'teaspoon' :  4.93,
                      'tsp' :  4.93,
                      'wineglass': 118.29}

secondary_conversion_dict = {'can': 354.882, #surprisingly decent assumption of a 12 oz can standard
                             'cube': 30,
                             'float' : 29.574, #assuming a float to be a pony/ounce
                             'g' : 1, #assuming gram; here as secondary measure to searc
                             'gr': 1, #assuming this is a misnomer abbeviation for gram
                             'gram' : 1,
                             'in' : 16.387, #this assumes cubic inches, which is almost certainly not the intention of the authors
                             'inch': 16.387}

ml_conversion_dict = {**primary_conversion_dict, **secondary_conversion_dict}

metric_words = list(primary_conversion_dict.keys())
odd_metric_words = list(secondary_conversion_dict.keys())


#since we're converting everything to parts, we'll leave "part" as it's own category
part_words = ['part', 'parts']


# there are some words that are not exact metrics but are still units. 
# for now, these will be listed as "ingrdients present" but not incorporated into ratios
nonmetric_words =  ['1', #count value
                    'bottle', # 12oz beer = 354.882 mL, bottle of wine = 750 mL, bottle of soda = 2000 mL
                    'chunks',
                    'count', #filler word where unit is implied'absent
                    'crushed', #a bad metric for ice
                    'fill',
                    'fillwith',
                    'garnish',
                    'glass',
                    'ground',
                    'juice',
                    'package',
                    'piece',
                    'rim',
                    'slice',
                    'sprig',
                    'stick',
                    'top',
                    'twist',
                    'wedge',
                    'whole']

column_semantics = {'151 proof rum':'rum',
                    '7-up':'lemon-lime soda',
                    'absinthe':'absinthe',
                    'absolut citron': 'lemon liqueur',
                    'absolut kurant': 'currant liqueur',
                    'absolut peppar': 'spicy liqueur',
                    'absolut vodka': 'vodka',
                    'advocaat': 'advocaat',
                    'agave syrup':'agave syrup',
                    'allspice':'allspice',
                    'amaretto':'amaretto',
                    'amaro montenegro': 'amaro',
                    'angostura bitters':'bitters',
                    'anis':'anise liqueur',
                    'anisette':'anise liqueur',
                    'aperol':'apertif wine',
                    'apfelkorn':'apple liqueur',
                    'apple': 'apple',
                    'apple brandy':'apple liqueur',
                    'apple juice':'apple juice',
                    'applejack':'apple liqueur',
                    'apricot brandy':'apricot liqueur', 
                    'apricot nectar': 'apricot liqueur',
                    'asafoetida':'fennel',
                    'añejo rum':'rum',
                    'bacardi limon' : 'lemon liqueur',
                    'bailey' :'irish cream',
                    'baileys irish cream':'irish cream',
                    'banana':'banana',
                    'banana liqueur' : 'banana liqueur',
                    'beer':'beer',
                    'benedictine':'herbal liqueur', #I love benedictine, but it should probably be generalized
                    'bitter lemon':'lemon',
                    'bitters':'bitters',
                    'black pepper':'black pepper',
                    'black sambuca':'anise liqueur',
                    'blackberries':'blackberries',
                    'blackberry brandy':'blackberry liqueur',
                    'blackcurrant cordial':'currant liqueur',
                    'blackstrap rum':'rum',
                    'blended scotch':'scotch',
                    'blended whiskey':'whiskey',
                    'blood orange':'orange',
                    'blue curacao':'curacao',
                    'bourbon' : 'whiskey', #may the gods forgive me
                    'brandy' : 'brandy',
                    'brown sugar':'sugar',
                    'butter':'butter',
                    'butterscotch schnapps' : 'butterscotch liqueur',
                    'cachaca':'rum', #might consider keeping as it's own thing
                    'campari':'campari',
                    'carbonated water': 'soda',
                    'cardamom':'cardamom',
                    'cayenne pepper':'pepper',
                    'celery salt':'salt',
                    'chambord raspberry liqueur':'raspberry liqueur',
                    'champagne':'champagne', #using 'champagne' for all bubbly
                    'cherry':'cherry',
                    'cherry brandy':'cherry liqueur',
                    'cherry heering':'cherry liqueur',
                    'cherry juice':'cherry',
                    'cherry liqueur':'cherry liqueur',
                    'chocolate':'chocolate',
                    'chocolate liqueur':'chocolate liqueur',
                    'chocolate syrup':'chocolate',
                    'cider':'apple juice',
                    'cinnamon':'cinnamon',
                    'cloves':'cloves', #going to keep all spices distinct. NOTE: might create taxonomy to level them up
                    'club soda':'soda',
                    'coca-cola':'cola',
                    'cocoa powder':'chocolate',
                    'coconut liqueur':'coconut liqueur',
                    'coconut milk':'coconut milk',
                    'coconut syrup':'simple syrup',
                    'coffee':'coffee',
                    'coffee brandy':'coffee liqueur',
                    'coffee liqueur':'coffee liqueur',
                    'cognac':'cognac',
                    'cointreau':'orange liqueur',
                    'condensed milk':'cream',
                    'coriander':'coriander',
                    'corn syrup':'simple syrup',
                    'corona':'beer',
                    'cranberry juice':'cranberry juice',
                    'cranberry vodka':'cranberry liqueur',
                    'cream':'cream',
                    'cream of coconut':'coconut milk',
                    'creme de banane':'banana liqueur',
                    'creme de cacao':'chocolate liqueur',
                    'creme de cassis':'currant liqueur',
                    'creme de mure':'blackberry liqueur',
                    'crown royal':'rum',
                    'cucumber':'cucumber',
                    'cumin seed':'cumin',
                    'daiquiri mix':'simple syrup',
                    'dark creme de cacao':'chocolate liqueur',
                    'dark rum':'rum',
                    'demerara sugar':'sugar',
                    'dr. pepper':'cola',
                    'drambuie':'scotch',
                    'dry vermouth':'vermouth',
                    'dubonnet rouge':'apertif wine',
                    'egg':'egg',
                    'egg white':'egg',
                    'egg yolk':'egg',
                    'elderflower cordial':'elderflower liqueur',
                    'espresso':'coffee',
                    'everclear':'grain spirit',
                    'falernum':'simple syrup',
                    'figs':'figs',
                    'firewater':'grain spirit',
                    'food coloring':'dye',
                    'frangelico':'hazelnut liqueur',
                    'fresh lemon juice':'lemon juice',
                    'fresh lime juice':'lime juice',
                    'fruit':'fruit',
                    'fruit juice':'fruit juice',
                    'fruit punch':'fruit juice',
                    'galliano':'herbal liqueur',
                    'gin':'gin',
                    'ginger':'ginger',
                    'ginger ale':'ginger ale',
                    'ginger beer':'ginger ale',
                    'ginger syrup':'simple syrup',
                    'godiva liqueur':'chocolate liqueur',
                    'gold rum':'rum',
                    'goldschlager':'cinnamon liqueur',
                    'grain alcohol':'grain alcohol',
                    'grand marnier':'orange liqueur',
                    'grape juice':'grape juice',
                    'grape soda':'grape juice',
                    'grapefruit juice':'grapefruit juice',
                    'green chartreuse':'chartreuse',
                    'green creme de menthe':'mint liqueur',
                    'grenadine':'grenadine',
                    'guinness stout':'beer',
                    'half-and-half':'cream',
                    'heavy cream':'cream',
                    'honey':'honey',
                    'honey syrup':'honey',
                    'hot chocolate':'chocolate',
                    'hot damn':'cinnamon liqueur',
                    'hot sauce':'pepper',
                    'ice':'ice',
                    'iced tea':'tea',
                    'irish cream':'irish cream',
                    'irish whiskey':'whiskey',
                    'islay single malt scotch':'scotch',
                    'jack daniels':'whiskey',
                    'jagermeister':'herbal liqueur',
                    'jello':'jello',
                    'jim beam':'whiskey',
                    'johnnie walker':'scotch',
                    'jägermeister':'herbal liqueur',
                    'kahlua':'coffee liqueur',
                    'kiwi':'kiwi',
                    'kiwi liqueur':'kiwi liqueur',
                    'kool-aid':'fruit juice',
                    'lager':'beer',
                    'lavender':'lavender',
                    'lemon':'lemon',
                    'lemon juice':'lemon juice',
                    'lemon peel':'lemon',
                    'lemon-lime soda':'lemon-lime soda',
                    'lemonade':'lemon-lime soda',
                    'light cream':'cream',
                    'light rum':'rum',
                    'lillet':'apertif wine',
                    'lillet blanc':'apertif wine',
                    'lime':'lime',
                    'lime juice':'lime juice',
                    'lime peel':'lime',
                    'lime vodka':'lime liqueur',
                    'limeade':'lime juice',
                    'malibu rum':'coconut liqueur',
                    'mango':'mango',
                    'maple syrup':'simple syrup',
                    'maraschino cherry':'cherry',
                    'maraschino liqueur':'cherry liqueur',
                    'marshmallows':'marshmallows',
                    'melon liqueur':'melon liqueur',
                    'mezcal':'mezcal',
                    'midori melon liqueur':'melon liqueur',
                    'milk':'milk',
                    'mint':'mint',
                    'mountain dew':'lemon-lime soda',
                    'nutmeg':'nutmeg',
                    'olive':'olive',
                    'olive brine':'olive brine',
                    'orange':'orange',
                    'orange bitters':'bitters',
                    'orange curacao':'orange liqueur',
                    'orange juice':'orange juice',
                    'orange peel':'orange',
                    'orange spiral':'orange',
                    'oreo cookie':'cookie',
                    'orgeat syrup':'simple syrup', 
                    'ouzo':'anise liqueur',
                    'papaya':'papaya',
                    'passion fruit juice':'passion fruit juice',
                    'passion fruit syrup':'passion fruit juice',
                    'passoa':'passion fruit liqueur',
                    'peach bitters':'bitters',
                    'peach brandy':'peach liqueur',
                    'peach nectar':'peach liqueur',
                    'peach schnapps':'peach liqueur',
                    'peach vodka':'peach liqueur',
                    'peachtree schnapps':'peach liqueur',
                    'pepper':'pepper',
                    'peppermint extract':'mint',
                    'pepsi cola':'cola',
                    'pernod':'anise liqueur',
                    'peychaud bitters':'bitters',
                    'pina colada mix':'simple syrup',
                    'pineapple':'pineapple',
                    'pineapple juice':'pineapple juice',
                    'pineapple syrup':'simple syrup',
                    'pink lemonade':'lemon-lime soda',
                    'pisang ambon':'banana liqueur',
                    'pisco':'pisco',
                    'pomegranate juice':'grenadine',
                    'port':'apertif wine',
                    'powdered sugar':'sugar',
                    'prosecco':'champagne',
                    'raspberry liqueur':'raspberry liqueur',
                    'raspberry syrup':'simple syrup',
                    'raspberry vodka':'raspberry liqueur',
                    'red chili flakes':'pepper',
                    'red wine':'wine',
                    'ricard':'anise liqueur',
                    'root beer':'cola',
                    'rose':'wine',
                    'rosemary':'rosemary',
                    'rosemary syrup':'simple syrup',
                    'roses sweetened lime juice':'lime juice',
                    'rosso vermouth':'vermouth',
                    'ruby port':'apertif wine',
                    'rum':'rum',
                    'rumple minze':'mint liqueur',
                    'rye whiskey':'whiskey',
                    'salt':'salt',
                    'sambuca':'anise liqueur',
                    'sarsaparilla':'cola',
                    'schweppes russchian':'ginger ale',
                    'scotch':'scotch',
                    'sherry':'apertif wine',
                    'sirup of roses':'simple syrup',
                    'sloe gin':'sloe gin',
                    'soda water':'soda',
                    'sour mix':'simple syrup',
                    'southern comfort':'whiskey',
                    'soy sauce':'soy sauce',
                    'spiced rum':'rum',
                    'sprite':'lemon-lime soda',
                    'st. germain':'elderflower liqueur',
                    'strawberries':'strawberries',
                    'strawberry liqueur':'strawberry liqueur',
                    'strawberry schnapps':'strawberry liqueur',
                    'sugar':'sugar',
                    'sugar syrup':'simple syrup',
                    'surge':'lemon-lime soda',
                    'sweet and sour':'simple syrup',
                    'sweet vermouth':'vermouth',
                    'tabasco sauce':'hot sauce',
                    'tea':'tea',
                    'tennessee whiskey':'whiskey',
                    'tequila':'tequila',
                    'thyme':'thyme',
                    'tia maria':'coffee liqueur',
                    'tomato juice':'tomato juice',
                    'tonic water':'tonic',
                    'triple sec':'orange liqueur',
                    'vanilla':'vanilla',
                    'vanilla extract':'vanilla',
                    'vanilla ice-cream':'ice-cream',
                    'vanilla syrup':'simple syrup',
                    'vanilla vodka':'vanilla liqueur',
                    'vermouth':'vermouth',
                    'vodka':'vodka',
                    'water':'water',
                    'whipped cream':'cream',
                    'whipping cream':'cream',
                    'whiskey':'whiskey',
                    'whisky':'whiskey',
                    'white creme de menthe':'mint liqueur',
                    'white rum':'rum',
                    'white wine':'wine',
                    'wild turkey':'whiskey',
                    'wine':'wine',
                    'worcestershire sauce':'worcestershire sauce',
                    'wormwood':'absinthe',
                    'yellow chartreuse':'chartreuse',
                    'yoghurt':'yogurt',
                    'yukon jack':'whiskey',
                    'zima':'lemon-lime soda'}